---
title: Large thermoelastic effect in martensitic phase of ferroelastic alloys for high efficiency heat pumping
authors: [Qiao Li, Zhongzheng Deng, Aslan Ahadi, Kangjie Chu, Jie Yan, Kai Ming Huang, Sixia Hu, Yang Ren, Binbin He, Qingping Sun]
author_notes: []
date: '2025-05-15T00:00:00Z'
doi: 10.1038/s41467-025-59720-3
publishDate: '2025-05-15T00:00:00Z'
publication_types: [article-journal]
publication: Nature Communications
publication_short: ''
abstract: Solid state heat pumping using latent heat from first order ferroic phase transitions is a promising green alternative to traditional vapor compression technology. However, the intrinsic phase transition hysteresis poses a limitation on heat pumping energy efficiency. Here, we propose heat pumping using reversible heat from anhysteretic elastic deformation in martensitic phase of ferroelastic alloys. Conventionally, this thermoelastic effect (TeE) is considered too weak to be practical. But we find that in [100]-textured Ti78Nb22 martensitic polycrystals, the TeE can produce a large adiabatic temperature change (∆Tad) of 4−5 K at 413−473 K due to macroscopic large linear thermal expansion (αl = 10−4/K). This large TeE not only far exceeds those of ordinary metals ( $$\Delta {T}_{{ad}}\approx 0.2K$$ ) but also brings a material-level energy efficiency that reaches about 90% of the Carnot theoretical limit. In other ferroelastic martensitic alloys with larger intrinsic αl (up to 5.4 × 10−4/K), the TeE is predicted to bring an even larger ∆Tad (up to 22 K) while maintaining relatively high efficiency. Our findings offer a non-phase-transition-based way for high efficiency solid state heat pumping. The authors discover a large caloric effect generated by pure elastic deformation in martensitic alloys, offering a strategy for ecofriendly and energy-efficient heat pumping.
summary: '**_Nature Communications._** (2025-05) Solid state heat pumping using latent heat from first order ferroic phase transitions is a promising green alternative to traditional vapor compression technology. However, the intrinsic phase transition hysteresis poses a limitation on heat pumping energy efficiency.'
tags: [publication, journal]
featured: false
url_pdf: https://www.nature.com/articles/s41467-025-59720-3.pdf
url_code: ''
url_dataset: ''
url_poster: ''
url_project: ''
url_slides: ''
url_source: ''
url_video: ''
image: {caption: '', focal_point: '', preview_only: false}
projects: []
slides: ''
auto_generated: true
enriched: 2026-09-27 openalex score=1.000
---

